### ISSUE TITLE
Uploads are broken since latest deployment

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3755]
None of the images are showing up for any of my recent uploads after the deployment.

https://danbooru.donmai.us/posts/3164754
https://danbooru.donmai.us/posts/3164751

**Comment by r888888888** [comment]
Fixed in cd043c4868788c29eb2d0a5dc02c01639826c109 and files have been downloaded and redistributed. I'm still curious why some uploads are stuck in preprocessed.

**Comment by BrokenEagle** [comment]
All of the affected uploads still have no preview image:

https://danbooru.donmai.us/posts/3164754
https://danbooru.donmai.us/posts/3164753
https://danbooru.donmai.us/posts/3164752
https://danbooru.donmai.us/posts/3164751
https://danbooru.donmai.us/posts/3164750
https://danbooru.donmai.us/posts/3164749
https://danbooru.donmai.us/posts/3164748
https://danbooru.donmai.us/posts/3164747
https://danbooru.donmai.us/posts/3164746
https://danbooru.donmai.us/posts/3164745

The following still have no sample or fullsize image:

https://danbooru.donmai.us/posts/3164754
https://danbooru.donmai.us/posts/3164749

**Comment by BrokenEagle** [comment]
A couple more recent uploads are broken completely (full/sample/preview):

https://danbooru.donmai.us/posts/3165014
https://danbooru.donmai.us/posts/3165004

**Comment by BrokenEagle** [comment]
Some more broken:

https://danbooru.donmai.us/posts/3165059
https://danbooru.donmai.us/posts/3165060
https://danbooru.donmai.us/posts/3165061
https://danbooru.donmai.us/posts/3165062

**Comment by BrokenEagle** [comment]
More:
https://danbooru.donmai.us/posts/3165117
https://danbooru.donmai.us/posts/3165116
https://danbooru.donmai.us/posts/3165115
https://danbooru.donmai.us/posts/3165114

**Comment by r888888888** [comment]
I've run a script to search for missing files and redownload+redistribute them.

**Comment by BrokenEagle** [comment]
Yeah, it seems like the only two broken images remaining are:

https://danbooru.donmai.us/posts/3164749
https://danbooru.donmai.us/posts/3165059

**Comment by r888888888** [comment]
3164749 unfortunately has no source.
3165059 for whatever reason is failing.

**Comment by BrokenEagle** [comment]
For the paid reward with no source (post 3164749), the uploader posted a link where it can be downloaded on [forum #147981](https://danbooru.donmai.us/forum_posts/147981).

**Comment by BrokenEagle** [comment]
Some more broken:

https://danbooru.donmai.us/posts/3165527
https://danbooru.donmai.us/posts/3165523
https://danbooru.donmai.us/posts/3165507

**Comment by deusexcalamus** [comment]
The correct source for 3165059 is https://pbs.twimg.com/media/DZ_bw3kUQAEqwo8.jpg

**Comment by r888888888** [comment]
3165059 has been restored.

**Comment by BrokenEagle** [comment]
Some more:

https://danbooru.donmai.us/posts/3168998
https://danbooru.donmai.us/posts/3168988
https://danbooru.donmai.us/posts/3168987

**Comment by hakusaro** [comment]
Another: https://danbooru.donmai.us/posts/3170046

**Comment by r888888888** [comment]
These have been fixed.

**Comment by deusexcalamus** [comment]
And another https://danbooru.donmai.us/posts/3168988

**Comment by hakusaro** [comment]
Also dead: https://danbooru.donmai.us/posts/3172709

**Comment by r888888888** [comment]
Fixed.

**Comment by BrokenEagle** [comment]
Another dead:

https://danbooru.donmai.us/posts/3183335

**Comment by evazion** [comment]
I think there's a race condition in cleaning up abandoned uploads that are later retried.

[There were two attempts to upload the same file](https://danbooru.donmai.us/uploads?search%5Bsource_matches%5D=https%3A%2F%2Fi.pximg.net%2Fimg-original%2Fimg%2F2017%2F08%2F07%2F00%2F04%2F28%2F64265823_p20.png). The second attempt was 28 minutes after the first attempt. 30 minutes after the first attempt, the file was deleted because the upload was abandoned. The likely deleted the file that was now in use again for the second upload attempt.

**Comment by nonamethanks** [comment]
@r888888888 I'm still getting broken uploads when I leave tabs open for 10+ minutes before submitting. And if I reload the page right before I submit, to make sure the post is re-processed, the post gets uploaded correctly but I get sent to a full-page error message that says 

```
ActionView::Template::Error exception raised
No route matches {:action=>"show", :controller=>"posts", :id=>nil}, possible unmatched constraints: [:id]
app/views/uploads/show.html.erb:23:in `_app_views_uploads_show_html_erb__2572185917533766648_46954663396660'
``` 
Some posts that failed:
https://danbooru.donmai.us/posts/3194679  
https://danbooru.donmai.us/posts/3194681

**Comment by r888888888** [comment]
Those two have been fixed. I've searched for missing files in the past 6 weeks and it didn't find anything else.

I'll do a deeper dive and try to figure out what's causing this.

**Comment by r888888888** [comment]
I'll extend the grace period for deleting preprocessed files to 24 hours (previously 30 minutes).

**Comment by BrokenEagle** [comment]
Another post reported failing ([forum #149350](https://danbooru.donmai.us/forum_posts/149350)):

https://danbooru.donmai.us/posts/3207176

**Comment by Iratu** [comment]
I've got a list of preprocessed images, but they're not processing, is it possible to delete those entries or somehow fix them?
https://atfbooru.ninja/uploads?search%5Bstatus%5D=preprocessed

**Comment by r888888888** [comment]
The `DailyMaintenance` script deletes all uploads older than a day.
